/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.entity.query.model;

public class AVClause extends EClause {

  private KClauseList a;
  private KClauseList v;
  private int op;

  public AVClause (KClauseList a, KClauseList v, int op) {
    this.a = a;
    if (a != null) a.setParent(this);
    this.v = v;
    if (v != null) v.setParent(this);
    this.op = op;
  }

  public KClauseList getA() {
    return a;
  }

  public void setA(KClauseList a) {
    this.a = a;
  }

  public KClauseList getV() {
    return v;
  }

  public void setV(KClauseList v) {
    this.v = v;
  }

  public int getOp() {
    return op;
  }

  public void setOp(int op) {
    this.op = op;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (a != null) a.accept(visitor);
    if (v != null) v.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (a != null) a.traverseTopDown(visitor);
    if (v != null) v.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (a != null) a.traverseBottomUp(visitor);
    if (v != null) v.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("AVClause(\n");
      if (a != null)
        buffer.append(a.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (v != null)
        buffer.append(v.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+op);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [AVClause]");
    return buffer.toString();
  }
}
