/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.entity.query.model;

public class EQuery extends Clause {

  private String field;
  private EClauseList eclauses;
  private int op;

  public EQuery (String field, EClauseList eclauses, int op) {
    this.field = field;
    this.eclauses = eclauses;
    if (eclauses != null) eclauses.setParent(this);
    this.op = op;
  }

  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public EClauseList getEclauses() {
    return eclauses;
  }

  public void setEclauses(EClauseList eclauses) {
    this.eclauses = eclauses;
  }

  public int getOp() {
    return op;
  }

  public void setOp(int op) {
    this.op = op;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (eclauses != null) eclauses.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (eclauses != null) eclauses.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (eclauses != null) eclauses.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("EQuery(\n");
    buffer.append("  "+tab+field);
    buffer.append("\n");
      if (eclauses != null)
        buffer.append(eclauses.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+op);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [EQuery]");
    return buffer.toString();
  }
}
