/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.entity.query.model;

public class KQuery extends Clause {

  private String field;
  private KClauseList kclauses;
  private int op;

  public KQuery (String field, KClauseList kclauses, int op) {
    this.field = field;
    this.kclauses = kclauses;
    if (kclauses != null) kclauses.setParent(this);
    this.op = op;
  }

  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public KClauseList getKclauses() {
    return kclauses;
  }

  public void setKclauses(KClauseList kclauses) {
    this.kclauses = kclauses;
  }

  public int getOp() {
    return op;
  }

  public void setOp(int op) {
    this.op = op;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (kclauses != null) kclauses.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (kclauses != null) kclauses.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (kclauses != null) kclauses.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("KQuery(\n");
    buffer.append("  "+tab+field);
    buffer.append("\n");
      if (kclauses != null)
        buffer.append(kclauses.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+op);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [KQuery]");
    return buffer.toString();
  }
}
