/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.entity.query.model;

public interface Operator {

  public final static int PLUS = 0;
  public final static int MINUS = 1;
  public final static int NONE = 2;

}
