/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */

package org.sindice.siren.qparser.entity.query.model;

public interface SyntaxNode {

  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);

  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
