/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.entity.query.model;

public abstract class VisitorAdaptor implements Visitor {

  public void visit(Query query) { visit(); }
  public void visit(EClauseList eClauseList) { visit(); }
  public void visit(KClauseList kClauseList) { visit(); }
  public void visit(KClause kClause) { visit(); }
  public void visit(Clause clause) { visit(); }
  public void visit(EQuery eQuery) { visit(); }
  public void visit(KQuery kQuery) { visit(); }
  public void visit(EClause eClause) { visit(); }
  public void visit(AVClause aVClause) { visit(); }
  public void visit(AClause aClause) { visit(); }
  public void visit(VClause vClause) { visit(); }

  public void visit() { }

}
