/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.entity.query.model;

public interface Visitor {

  public void visit(Query query);
  public void visit(EClauseList eClauseList);
  public void visit(KClauseList kClauseList);
  public void visit(KClause kClause);
  public void visit(Clause clause);
  public void visit(EQuery eQuery);
  public void visit(KQuery kQuery);
  public void visit(EClause eClause);
  public void visit(AVClause aVClause);
  public void visit(AClause aClause);
  public void visit(VClause vClause);

}
