
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 09 17:48:53 IST 2010
//----------------------------------------------------

package org.sindice.siren.qparser.entity;

/** CUP generated interface containing symbol constants. */
public interface EntityQParserSymbols {
  /* terminals */
  public static final int MINUS = 3;
  public static final int TERM = 9;
  public static final int LPAR = 4;
  public static final int WILDCARD = 8;
  public static final int EQUAL = 6;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int error = 1;
  public static final int QUOTE = 7;
  public static final int RPAR = 5;
}

