/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.ntriple.query.model;

public abstract class Expression implements SyntaxNode {

  private org.apache.lucene.search.Query query;
  private java.util.Map queries;
  private SyntaxNode parent;

  public TriplePattern getTp() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setTp(TriplePattern tp) {
    throw new ClassCastException("tried to call abstract method");
  }

  public NTripleQuery getQ() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setQ(NTripleQuery q) {
    throw new ClassCastException("tried to call abstract method");
  }

  public org.apache.lucene.search.Query getQuery() {
    return query;
  }

  public void setQuery(org.apache.lucene.search.Query query) {
    this.query = query;
  }

  public java.util.Map getQueries() {
    return queries;
  }

  public void setQueries(java.util.Map queries) {
    this.queries = queries;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public abstract void accept(Visitor visitor);
  public abstract void childrenAccept(Visitor visitor);
  public abstract void traverseTopDown(Visitor visitor);
  public abstract void traverseBottomUp(Visitor visitor);
  public String toString() {
    return toString("");
  }

  public abstract String toString(String tab);
}
