/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.ntriple.query.model;

public interface Operator {

  public final static int AND = 0;
  public final static int OR = 1;
  public final static int MINUS = 2;

}
