/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.ntriple.query.model;

public class UnaryClause extends Clause {

  private Expression expr;

  public UnaryClause (Expression expr) {
    this.expr = expr;
    if (expr != null) expr.setParent(this);
  }

  public Expression getExpr() {
    return expr;
  }

  public void setExpr(Expression expr) {
    this.expr = expr;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (expr != null) expr.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (expr != null) expr.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (expr != null) expr.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("UnaryClause(\n");
      if (expr != null)
        buffer.append(expr.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [UnaryClause]");
    return buffer.toString();
  }
}
