/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.ntriple.query.model;

public interface Visitor {

  public void visit(TriplePattern triplePattern);
  public void visit(NTripleQuery nTripleQuery);
  public void visit(ClauseQuery clauseQuery);
  public void visit(EmptyQuery emptyQuery);
  public void visit(Clause clause);
  public void visit(UnaryClause unaryClause);
  public void visit(BinaryClause binaryClause);
  public void visit(NestedClause nestedClause);
  public void visit(Expression expression);
  public void visit(SimpleExpression simpleExpression);
  public void visit(QueryExpression queryExpression);
  public void visit(Value value);
  public void visit(Literal literal);
  public void visit(LiteralPattern literalPattern);
  public void visit(Resource resource);
  public void visit(URIPattern uRIPattern);
  public void visit(Wildcard wildcard);

}
