/*
 * Generated by classgen, version 1.3
 * 12/04/11 12:12
 */
package org.sindice.siren.qparser.ntriple.query.model;

public abstract class VisitorAdaptor implements Visitor {

  public void visit(TriplePattern triplePattern) { visit(); }
  public void visit(NTripleQuery nTripleQuery) { visit(); }
  public void visit(ClauseQuery clauseQuery) { visit(); }
  public void visit(EmptyQuery emptyQuery) { visit(); }
  public void visit(Clause clause) { visit(); }
  public void visit(UnaryClause unaryClause) { visit(); }
  public void visit(BinaryClause binaryClause) { visit(); }
  public void visit(NestedClause nestedClause) { visit(); }
  public void visit(Expression expression) { visit(); }
  public void visit(SimpleExpression simpleExpression) { visit(); }
  public void visit(QueryExpression queryExpression) { visit(); }
  public void visit(Value value) { visit(); }
  public void visit(Literal literal) { visit(); }
  public void visit(LiteralPattern literalPattern) { visit(); }
  public void visit(Resource resource) { visit(); }
  public void visit(URIPattern uRIPattern) { visit(); }
  public void visit(Wildcard wildcard) { visit(); }

  public void visit() { }

}
